# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_passwd.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSetPasswd(object):
    def setupUi(self, DialogSetPasswd):
        DialogSetPasswd.setObjectName("DialogSetPasswd")
        DialogSetPasswd.resize(452, 327)
        self.widget = QtWidgets.QWidget(DialogSetPasswd)
        self.widget.setGeometry(QtCore.QRect(10, 10, 431, 311))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_passwd = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_passwd.sizePolicy().hasHeightForWidth())
        self.lb_passwd.setSizePolicy(sizePolicy)
        self.lb_passwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_passwd.setObjectName("lb_passwd")
        self.horizontalLayout.addWidget(self.lb_passwd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.le_passwd = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_passwd.sizePolicy().hasHeightForWidth())
        self.le_passwd.setSizePolicy(sizePolicy)
        self.le_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_passwd.setClearButtonEnabled(False)
        self.le_passwd.setObjectName("le_passwd")
        self.horizontalLayout.addWidget(self.le_passwd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_confirm = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_confirm.sizePolicy().hasHeightForWidth())
        self.lb_confirm.setSizePolicy(sizePolicy)
        self.lb_confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_confirm.setObjectName("lb_confirm")
        self.horizontalLayout_2.addWidget(self.lb_confirm)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.le_passwd_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_passwd_2.sizePolicy().hasHeightForWidth())
        self.le_passwd_2.setSizePolicy(sizePolicy)
        self.le_passwd_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_passwd_2.setClearButtonEnabled(False)
        self.le_passwd_2.setObjectName("le_passwd_2")
        self.horizontalLayout_2.addWidget(self.le_passwd_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 5)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_ok = QtWidgets.QPushButton(self.widget)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_3.addWidget(self.btn_ok)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(DialogSetPasswd)
        QtCore.QMetaObject.connectSlotsByName(DialogSetPasswd)

    def retranslateUi(self, DialogSetPasswd):
        _translate = QtCore.QCoreApplication.translate
        DialogSetPasswd.setWindowTitle(_translate("DialogSetPasswd", "设置新密码"))
        self.lb_passwd.setText(_translate("DialogSetPasswd", "输入新密码"))
        self.lb_confirm.setText(_translate("DialogSetPasswd", "确认新密码"))
        self.btn_ok.setText(_translate("DialogSetPasswd", "确认"))
