# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_password.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSetPasswd(object):
    def setupUi(self, DialogSetPasswd):
        DialogSetPasswd.setObjectName("DialogSetPasswd")
        DialogSetPasswd.resize(441, 180)
        DialogSetPasswd.setMinimumSize(QtCore.QSize(441, 180))
        DialogSetPasswd.setMaximumSize(QtCore.QSize(441, 180))
        self.widget = QtWidgets.QWidget(DialogSetPasswd)
        self.widget.setGeometry(QtCore.QRect(12, 12, 421, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_passwd = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_passwd.sizePolicy().hasHeightForWidth())
        self.lb_passwd.setSizePolicy(sizePolicy)
        self.lb_passwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_passwd.setObjectName("lb_passwd")
        self.horizontalLayout.addWidget(self.lb_passwd)
        self.le_passwd = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_passwd.sizePolicy().hasHeightForWidth())
        self.le_passwd.setSizePolicy(sizePolicy)
        self.le_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_passwd.setClearButtonEnabled(False)
        self.le_passwd.setObjectName("le_passwd")
        self.horizontalLayout.addWidget(self.le_passwd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_confirm = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_confirm.sizePolicy().hasHeightForWidth())
        self.lb_confirm.setSizePolicy(sizePolicy)
        self.lb_confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_confirm.setObjectName("lb_confirm")
        self.horizontalLayout_2.addWidget(self.lb_confirm)
        self.le_confirm = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_confirm.sizePolicy().hasHeightForWidth())
        self.le_confirm.setSizePolicy(sizePolicy)
        self.le_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_confirm.setClearButtonEnabled(False)
        self.le_confirm.setObjectName("le_confirm")
        self.horizontalLayout_2.addWidget(self.le_confirm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_ok = QtWidgets.QPushButton(self.widget)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_3.addWidget(self.btn_ok)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(DialogSetPasswd)
        QtCore.QMetaObject.connectSlotsByName(DialogSetPasswd)

    def retranslateUi(self, DialogSetPasswd):
        _translate = QtCore.QCoreApplication.translate
        DialogSetPasswd.setWindowTitle(_translate("DialogSetPasswd", "设置新密码"))
        self.lb_passwd.setText(_translate("DialogSetPasswd", "输入新密码"))
        self.lb_confirm.setText(_translate("DialogSetPasswd", "确认新密码"))
        self.btn_ok.setText(_translate("DialogSetPasswd", "确认"))
